# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0219b019fe6942244b290fe44e4af7cda266e8f8e0971c6e8c221e7e2a0e17afbd0be3befab8c3c9f08b17b5aff53c8e5cffd0ad985ad7abe627a8a4f3443f41

test:
  secret_key_base: d88ce0a48b435a2bb2565413d45d2058d8cc924abe1aea56356a63a480ffc1d828dc669dea59a5c801d30c72cf652d39d6ca301c695d604aefabb8d7eaa764df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
